[package]
name = "content-aware-resizing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image_energy = "0.1.3"
image = "0.24.2"
structopt = "0.3.26"
rayon = "1.5.3"